#This is workflow name
name: Adnan khan

# Runs on a trigger
on: 
  workflow_dispatch: 
    
#these are jobs inside workflow
jobs:

#These are the name of jobs
  greet:
  
    #This is github runner, every jobs runs on a runners
    runs-on: ubuntu-latest
    steps:
      - name: say my name
        run: echo " ADNAN KHAN"

      - name: say my nickname
        run : echo "$USER"
        
    

